/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels;

/**
 *
 * @author ADMIN
 */
public class panelHome extends javax.swing.JPanel {

    /**
     * Creates new form panelHome
     */
    public panelHome() {
        initComponents();
        mainButton2.setLabel("Explore");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        contentPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        headerText1 = new javax.swing.JLabel();
        mainButton2 = new component.mainButton();
        jLabel3 = new javax.swing.JLabel();

        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setPreferredSize(new java.awt.Dimension(900, 519));

        jScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane.setAlignmentX(0.0F);
        jScrollPane.setAlignmentY(0.0F);
        jScrollPane.setPreferredSize(new java.awt.Dimension(1200, 600));
        jScrollPane.setViewportView(null);

        contentPanel.setBackground(new java.awt.Color(231, 233, 205));
        contentPanel.setForeground(new java.awt.Color(255, 255, 255));
        contentPanel.setAlignmentX(0.0F);
        contentPanel.setAlignmentY(0.0F);
        contentPanel.setPreferredSize(new java.awt.Dimension(900, 2000));
        contentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 0, 52)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setLabelFor(contentPanel);
        jLabel1.setText("with art and design");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 64));
        contentPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        headerText1.setFont(new java.awt.Font("Baskerville Old Face", 0, 52)); // NOI18N
        headerText1.setForeground(new java.awt.Color(0, 51, 51));
        headerText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerText1.setLabelFor(contentPanel);
        headerText1.setText("Transforming spaces");
        headerText1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        headerText1.setPreferredSize(new java.awt.Dimension(500, 64));
        contentPanel.add(headerText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 541, -1));

        mainButton2.setForeground(new java.awt.Color(255, 255, 255));
        mainButton2.setText("Discover");
        mainButton2.setBorderColor(new java.awt.Color(242, 242, 242));
        mainButton2.setColor(new java.awt.Color(153, 153, 0));
        mainButton2.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        mainButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainButton2ActionPerformed(evt);
            }
        });
        contentPanel.add(mainButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 140, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img_homepage.jpg"))); // NOI18N
        contentPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 1200, -1));

        jScrollPane.setViewportView(contentPanel);

        add(jScrollPane);
    }// </editor-fold>//GEN-END:initComponents

    private void mainButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mainButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel headerText1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane;
    private component.mainButton mainButton2;
    // End of variables declaration//GEN-END:variables
}
