/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels;

import component.artistCard;
import dataModel.artistModel;
import java.util.List;
import dataModel.ArtistDAO;
import java.awt.Dimension;
import java.awt.GridLayout;

/**
 *
 * @author ADMIN
 */
public class panelArtist extends javax.swing.JPanel {

    /**
     * Creates new form panelHome
     */
    public panelArtist() {
        initComponents();
        fetchAndDisplayArtists();
    }
    
    private void fetchAndDisplayArtists() {
    ArtistDAO artistDAO = new ArtistDAO();
    List<artistModel> artists = artistDAO.getAllArtists();

    artistDisplay.setLayout(new GridLayout(0, 3, 20, 20)); // Added spacing
    artistDisplay.setOpaque(false);
    

    for (artistModel artist : artists) {
        artistCard cardPanel = new artistCard(artist);
        artistDisplay.add(cardPanel);
    }

    artistDisplay.revalidate();
    artistDisplay.repaint();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        contentPanel = new javax.swing.JPanel();
        headerText = new javax.swing.JLabel();
        artistDisplay = new javax.swing.JPanel();

        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setPreferredSize(new java.awt.Dimension(900, 519));

        jScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane.setAlignmentX(0.0F);
        jScrollPane.setAlignmentY(0.0F);
        jScrollPane.setPreferredSize(new java.awt.Dimension(1200, 600));
        jScrollPane.setViewportView(contentPanel);

        contentPanel.setBackground(new java.awt.Color(231, 233, 205));
        contentPanel.setForeground(new java.awt.Color(255, 255, 255));
        contentPanel.setAlignmentX(0.0F);
        contentPanel.setAlignmentY(0.0F);
        contentPanel.setPreferredSize(new java.awt.Dimension(900, 2000));
        contentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerText.setFont(new java.awt.Font("Baskerville Old Face", 0, 52)); // NOI18N
        headerText.setForeground(new java.awt.Color(0, 51, 51));
        headerText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerText.setLabelFor(contentPanel);
        headerText.setText("Artists");
        headerText.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        headerText.setPreferredSize(new java.awt.Dimension(500, 64));
        contentPanel.add(headerText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 541, -1));

        artistDisplay.setOpaque(false);
        artistDisplay.setPreferredSize(new java.awt.Dimension(800, 88));

        javax.swing.GroupLayout artistDisplayLayout = new javax.swing.GroupLayout(artistDisplay);
        artistDisplay.setLayout(artistDisplayLayout);
        artistDisplayLayout.setHorizontalGroup(
            artistDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        artistDisplayLayout.setVerticalGroup(
            artistDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1820, Short.MAX_VALUE)
        );

        contentPanel.add(artistDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 164, 900, 1820));

        jScrollPane.setViewportView(contentPanel);

        add(jScrollPane);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel artistDisplay;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel headerText;
    private javax.swing.JScrollPane jScrollPane;
    // End of variables declaration//GEN-END:variables
}
