/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels;

import component.artistCard;
import dataModel.artistModel;
import java.util.List;
import dataModel.ArtistDAO;
import java.awt.GridLayout;

/**
 *
 * @author ADMIN
 */
public class panelArtist extends javax.swing.JPanel {

    /**
     * Creates new form panelHome
     */
    public panelArtist() {
        initComponents();
        fetchAndDisplayArtists();
    }
    
    private void fetchAndDisplayArtists() {
    ArtistDAO artistDAO = new ArtistDAO();
        List<artistModel> artists = artistDAO.getAllArtists();

        contentPanel.setLayout(new GridLayout(0, 3));
        
        for (artistModel artist : artists) {
            artistCard cardPanel = new artistCard(artist);
            contentPanel.add(cardPanel);
        }
        
    contentPanel.revalidate();
    contentPanel.repaint();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        contentPanel = new javax.swing.JPanel();
        headerText = new javax.swing.JLabel();

        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setPreferredSize(new java.awt.Dimension(900, 519));

        jScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane.setAlignmentX(0.0F);
        jScrollPane.setAlignmentY(0.0F);
        jScrollPane.setPreferredSize(new java.awt.Dimension(1200, 600));
        jScrollPane.setViewportView(contentPanel);

        contentPanel.setBackground(new java.awt.Color(231, 233, 205));
        contentPanel.setForeground(new java.awt.Color(255, 255, 255));
        contentPanel.setAlignmentX(0.0F);
        contentPanel.setAlignmentY(0.0F);
        contentPanel.setPreferredSize(new java.awt.Dimension(900, 2000));

        headerText.setFont(new java.awt.Font("Baskerville Old Face", 0, 52)); // NOI18N
        headerText.setForeground(new java.awt.Color(0, 51, 51));
        headerText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerText.setLabelFor(contentPanel);
        headerText.setText("Artists");
        headerText.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        headerText.setPreferredSize(new java.awt.Dimension(500, 64));

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(headerText, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(headerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane.setViewportView(contentPanel);

        add(jScrollPane);
        jScrollPane.getAccessibleContext().setAccessibleParent(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel headerText;
    private javax.swing.JScrollPane jScrollPane;
    // End of variables declaration//GEN-END:variables
}
