/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package onlineartgallery;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class frmLogin extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
        formBg.setAlpha((float) 0.9);
        setBackground(new Color(0, 0, 0, 0));
        mainButton1.setLabel("Sign in");
        winButton.initEvent(frmLogin.this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formBg = new decoration.Background();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        signupBtn = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        mainButton1 = new component.mainButton();
        winButton = new component.winButton();
        nameText = new javax.swing.JLabel();
        imgBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Welcome Back!");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setText("Enter your information to sign in.");

        usernameLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        usernameLabel.setText("Username");

        usernameField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        usernameField.setMargin(new java.awt.Insets(2, 12, 2, 6));

        passwordLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        passwordLabel.setText("Password");

        signupBtn.setBackground(new java.awt.Color(242, 242, 242));
        signupBtn.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        signupBtn.setText("Sign Up");
        signupBtn.setBorder(null);

        passwordField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        passwordField.setMargin(new java.awt.Insets(2, 12, 2, 6));

        mainButton1.setBackground(new java.awt.Color(153, 153, 0));
        mainButton1.setForeground(new java.awt.Color(255, 255, 255));
        mainButton1.setText("Sign in");
        mainButton1.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        mainButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formBgLayout = new javax.swing.GroupLayout(formBg);
        formBg.setLayout(formBgLayout);
        formBgLayout.setHorizontalGroup(
            formBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBgLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(formBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passwordLabel)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(usernameLabel)
                    .addComponent(usernameField)
                    .addComponent(signupBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                    .addComponent(passwordField)
                    .addComponent(mainButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        formBgLayout.setVerticalGroup(
            formBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBgLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(24, 24, 24)
                .addComponent(usernameLabel)
                .addGap(8, 8, 8)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordLabel)
                .addGap(8, 8, 8)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(mainButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        getContentPane().add(formBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 430, 480));
        getContentPane().add(winButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, -1, -1));

        nameText.setFont(new java.awt.Font("Baskerville Old Face", 1, 48)); // NOI18N
        nameText.setForeground(new java.awt.Color(255, 255, 255));
        nameText.setText("T&T Art Gallery");
        getContentPane().add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));

        imgBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img_login.jpg"))); // NOI18N
        imgBg.setAlignmentY(0.0F);
        imgBg.setDisabledIcon(null);
        getContentPane().add(imgBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mainButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainButton1ActionPerformed
        // TODO add your handling code here:
        if (usernameField.getText().length() == 0 ||String.valueOf(passwordField.getPassword()).length() == 0) {
            JOptionPane.showMessageDialog(null, "Please input information","Message", JOptionPane.WARNING_MESSAGE);
            return;            
        }
        
        String connectionUrl = "jdbc:sqlserver://sql.bsite.net\\MSSQL2016;databaseName=htthuy_ArtGallery;user=htthuy_ArtGallery;password=012345678";
        try(Connection con = DriverManager.getConnection(connectionUrl)){
            
            String username = usernameField.getText();
            String password = String.valueOf(passwordField.getPassword());
            
            String SQL = "SELECT * FROM Users WHERE username=? AND password=?";
            PreparedStatement preparedStatement = con.prepareStatement(SQL);
            preparedStatement.setString(1, username);
            preparedStatement.setString(2, password);
 
            ResultSet rs = preparedStatement.executeQuery();
            
            if (rs.next()) {// Valid credentials
                frmMain frm = new frmMain();
                frm.setVisible(true);
                
                dispose();
                
            } else {
                // Invalid credentials
                JOptionPane.showMessageDialog(this, "Invalid username or password", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_mainButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private decoration.Background formBg;
    private javax.swing.JLabel imgBg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private component.mainButton mainButton1;
    private javax.swing.JLabel nameText;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton signupBtn;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    private component.winButton winButton;
    // End of variables declaration//GEN-END:variables
}
